### ISSUE TITLE
自作ライブラリ(python-lib-for-me)をインストールする際にエラーが発生する

### ISSUE THREAD

**Issue by silverag-corgi** [silverag-corgi/fgo-farm-report-collection#1]
```command
C:\Git\python\fgo-farm-report-collection>pipenv install -e "../python-lib-for-me"
Installing -e ../python-lib-for-me...
Error:  An error occurred while installing -e ../python-lib-for-me!
Error text: Obtaining file:///C:/Git/python/python-lib-for-me
            (from -r c:\users\silverag\appdata\local\temp\pipenv-fs3833_7-requirements\pipenv-vj7jdyi8-requirement.txt (line 1))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: 'C:\Git\python\fgo-farm-report-collection\.venv\Scripts\python.exe' 
            'C:\Git\python\fgo-farm-report-collection\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py'
            get_requires_for_build_wheel
            'C:\Users\silverag\AppData\Local\Temp\tmpzqw7k6td'
       cwd: C:\Git\python\python-lib-for-me
  Complete output (22 lines):
  Traceback (most recent call last):
    File "C:\Git\python\fgo-farm-report-collection\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Git\python\fgo-farm-report-collection\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Git\python\fgo-farm-report-collection\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-ej6nmo68\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-ej6nmo68\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-ej6nmo68\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\silverag\AppData\Local\Temp\pip-build-env-ej6nmo68\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 2, in <module>
      import python_lib_for_me
    File "C:\Git\python\python-lib-for-me\python_lib_for_me\__init__.py", line 1, in <module>
      from python_lib_for_me.date import *
    File "C:\Git\python\python-lib-for-me\python_lib_for_me\date.py", line 8, in <module>
      from dateutil.relativedelta import relativedelta
  ModuleNotFoundError: No module named 'dateutil'
  ----------------------------------------
WARNING: Discarding file:///C:/Git/python/python-lib-for-me
ERROR: Command errored out with exit status 1

Installation Failed
```

**Comment by silverag-corgi** [comment]
下記コマンドで解決した。

```command
C:\Git\python\fgo-farm-report-collection>pipenv run pip list -o
Package    Version Latest Type
---------- ------- ------ -----
pip        21.0.1  22.0.3 wheel
setuptools 60.5.0  60.7.1 wheel
tweepy     4.4.0   4.5.0  wheel
wheel      0.37.0  0.37.1 wheel


C:\Git\python\fgo-farm-report-collection>pipenv install pip setuptools wheel
Installing pip...
Adding pip to Pipfiles [packages]...
Installation Succeeded
Installing setuptools...
Adding setuptools to Pipfiles [packages]...
Installation Succeeded
Installing wheel...
Adding wheel to Pipfiles [packages]...
Installation Succeeded
Pipfile.lock (0ae45e) out of date, updating to (f0397f)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
 Locking...Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (f0397f)!
Installing dependencies from Pipfile.lock (f0397f)...
  ================================ 0/0 - 00:00:00
To activate this projects virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.


C:\Git\python\fgo-farm-report-collection>pipenv run pip list -o
Package Version Latest Type
------- ------- ------ -----
tweepy  4.4.0   4.5.0  wheel


C:\Git\python\fgo-farm-report-collection>pipenv run pip list
Package            Version
------------------ ---------
beautifulsoup4     4.10.0
certifi            2021.10.8
charset-normalizer 2.0.11
html5lib           1.1
idna               3.3
lxml               4.7.1
numpy              1.22.2
oauthlib           3.2.0
pandas             1.4.0
pip                22.0.3
python-dateutil    2.8.2
pytz               2021.3
requests           2.27.1
requests-oauthlib  1.3.1
setuptools         60.7.1
six                1.16.0
soupsieve          2.3.1
tweepy             4.4.0
urllib3            1.26.8
webencodings       0.5.1
wheel              0.37.1


C:\Git\python\fgo-farm-report-collection>pipenv install -e "../python-lib-for-me"
Installing -e ../python-lib-for-me...
Adding python-lib-for-me to Pipfiles [packages]...
Installation Succeeded
Pipfile.lock (f0397f) out of date, updating to (c0c2d5)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (c0c2d5)!
Installing dependencies from Pipfile.lock (c0c2d5)...
INFO:pep517.envbuild:Temporary build environment: C:\Users\silverag\AppData\Local\Temp\pep517-build-env-5q2i_xqp
INFO:pep517.envbuild:Temporary build environment: C:\Users\silverag\AppData\Local\Temp\pep517-build-env-yhunvwxl
  ================================ 0/0 - 00:00:00
To activate this projects virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```
